services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  backend-a:
    build: ./backend

    environment:
      SPRING_PROFILES_ACTIVE: dev

      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5400/whiteboard
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      JWT_PRIVATE_KEY_PATH: /keys/private.key
      JWT_PUBLIC_KEY_PATH: /keys/public.key

    volumes:
      - "C:/Users/amine/OneDrive/Bureau/keys:/keys:ro"

    depends_on:
      - redis

  backend-b:
    build: ./backend

    environment:
      SPRING_PROFILES_ACTIVE: dev

      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5400/whiteboard
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      JWT_PRIVATE_KEY_PATH: /keys/private.key
      JWT_PUBLIC_KEY_PATH: /keys/public.key

    volumes:
      - "C:/Users/amine/OneDrive/Bureau/keys:/keys:ro"

    depends_on:
      - redis

  api-gateway:
    build: ./api-gateway
    ports:
      - "8088:8080"

    environment:
      PORT: "8080"
      ROUTES_CONFIG_URI: "/app/configs/routes.json"

    depends_on:
      - backend-a
      - backend-b
  frontend:
    build: ./frontend
    ports:
      - "4200:80"

    depends_on:
      - api-gateway