services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  backend-a:
    build: ./backend
    ports:
      - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: dev

      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5400/whiteboard
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      JWT_PRIVATE_KEY_PATH: /keys/private.key
      JWT_PUBLIC_KEY_PATH: /keys/public.key

    volumes:
      - "C:/Users/amine/OneDrive/Bureau/keys:/keys:ro"

    depends_on:
      - redis

  backend-b:
    build: ./backend
    ports:
      - "8081:8080"

    environment:
      SPRING_PROFILES_ACTIVE: dev

      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5400/whiteboard
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      JWT_PRIVATE_KEY_PATH: /keys/private.key
      JWT_PUBLIC_KEY_PATH: /keys/public.key

    volumes:
      - "C:/Users/amine/OneDrive/Bureau/keys:/keys:ro"

    depends_on:
      - redis