spring.datasource.url= jdbc:postgresql://localhost:5400/whiteboard
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG