spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

jwt.private-key-path=${JWT_PRIVATE_KEY_PATH}
jwt.public-key-path=${JWT_PUBLIC_KEY_PATH}